seed: 42
n_splits: 5
use_group_kfold: false
pos_weight: 1.0

paths:
  csv: 'data/processed/datos_para_cnn_etiquetas - datos_para_cnn.csv.csv'
  heatmaps_dir: data/processed/heat_maps
  artifacts_dir: models
  reports_dir: reports

image:
  size: 224
  normalize: true
  augment:
    shift_pixels: 1
    gaussian_blur_sigma: 0.5
    random_affine_degrees: 10
    coarse_dropout_prob: 0.5
    mixup_alpha: 0.2

training:
  device: cpu
  batch_size: 64
  epochs: 5
  lr: 0.001
  weight_decay: 0.0001
  dropout: 0.5
  label_smoothing: 0.1
  backbone: resnet18
  clip_grad_norm: 1.0
  scheduler: onecycle  # ['onecycle', 'reduce_on_plateau', 'none']
  amp: false           # AMP solo en CUDA
  compile: false

features:
  numeric:
    - Min
    - Edad
    - PJ
    - Titular
    - "90 s"
    - Gls
    - Ass
    - xG
    - npxG
    - xAG
    - npxG+xAG
    - PrgC
    - PrgP
    - PrgR
  categorical:
    - Posicion
  drop:
    - Gls_total

loss:
  type: focal_loss

threshold: 0.5
